package DTOs;
// Generated May 29, 2012 11:19:30 AM by Hibernate Tools 3.2.1.GA


import java.math.BigDecimal;

/**
 * ClassRol generated by hbm2java
 */
public class ClassRol  implements java.io.Serializable {


     private BigDecimal id;
     private String seProductLine;
     private String className;
     private String codeVersion;
     private String codeDescription;
     private String refUrl;
     private BigDecimal executionOrder;
     private String code;
     private String seParametersName1;
     private String startCond1;
     private String startValue1;
     private String startMultiplier1;
     private String startUnit1;
     private String endCond1;
     private String endValue1;
     private String endMultiplier1;
     private String endUnit1;
     private String seParametersName2;
     private String startCond2;
     private String startValue2;
     private String startMultiplier2;
     private String startUnit2;
     private String endCond2;
     private String endValue2;
     private String endMultiplier2;
     private String endUnit2;
     private String seParametersName3;
     private String startCond3;
     private String startValue3;
     private String startMultiplier3;
     private String startUnit3;
     private String endCond3;
     private String endValue3;
     private String endMultiplier3;
     private String endUnit3;
     private String seParametersName4;
     private String startCond4;
     private String startValue4;
     private String startMultiplier4;
     private String startUnit4;
     private String endCond4;
     private String endValue4;
     private String endMultiplier4;
     private String endUnit4;
     private String seParametersName5;
     private String startCond5;
     private String startValue5;
     private String startMultiplier5;
     private String startUnit5;
     private String endCond5;
     private String endValue5;
     private String endMultiplier5;
     private String endUnit5;
     private BigDecimal featureId1;
     private BigDecimal featureId2;
     private BigDecimal featureId3;
     private BigDecimal featureId4;
     private BigDecimal featureId5;
     private BigDecimal plId;
     private BigDecimal clasId;

    public ClassRol() {
    }

	
    public ClassRol(BigDecimal id) {
        this.id = id;
    }
    public ClassRol(BigDecimal id, String seProductLine, String className, String codeVersion, String codeDescription, String refUrl, BigDecimal executionOrder, String code, String seParametersName1, String startCond1, String startValue1, String startMultiplier1, String startUnit1, String endCond1, String endValue1, String endMultiplier1, String endUnit1, String seParametersName2, String startCond2, String startValue2, String startMultiplier2, String startUnit2, String endCond2, String endValue2, String endMultiplier2, String endUnit2, String seParametersName3, String startCond3, String startValue3, String startMultiplier3, String startUnit3, String endCond3, String endValue3, String endMultiplier3, String endUnit3, String seParametersName4, String startCond4, String startValue4, String startMultiplier4, String startUnit4, String endCond4, String endValue4, String endMultiplier4, String endUnit4, String seParametersName5, String startCond5, String startValue5, String startMultiplier5, String startUnit5, String endCond5, String endValue5, String endMultiplier5, String endUnit5, BigDecimal featureId1, BigDecimal featureId2, BigDecimal featureId3, BigDecimal featureId4, BigDecimal featureId5, BigDecimal plId, BigDecimal clasId) {
       this.id = id;
       this.seProductLine = seProductLine;
       this.className = className;
       this.codeVersion = codeVersion;
       this.codeDescription = codeDescription;
       this.refUrl = refUrl;
       this.executionOrder = executionOrder;
       this.code = code;
       this.seParametersName1 = seParametersName1;
       this.startCond1 = startCond1;
       this.startValue1 = startValue1;
       this.startMultiplier1 = startMultiplier1;
       this.startUnit1 = startUnit1;
       this.endCond1 = endCond1;
       this.endValue1 = endValue1;
       this.endMultiplier1 = endMultiplier1;
       this.endUnit1 = endUnit1;
       this.seParametersName2 = seParametersName2;
       this.startCond2 = startCond2;
       this.startValue2 = startValue2;
       this.startMultiplier2 = startMultiplier2;
       this.startUnit2 = startUnit2;
       this.endCond2 = endCond2;
       this.endValue2 = endValue2;
       this.endMultiplier2 = endMultiplier2;
       this.endUnit2 = endUnit2;
       this.seParametersName3 = seParametersName3;
       this.startCond3 = startCond3;
       this.startValue3 = startValue3;
       this.startMultiplier3 = startMultiplier3;
       this.startUnit3 = startUnit3;
       this.endCond3 = endCond3;
       this.endValue3 = endValue3;
       this.endMultiplier3 = endMultiplier3;
       this.endUnit3 = endUnit3;
       this.seParametersName4 = seParametersName4;
       this.startCond4 = startCond4;
       this.startValue4 = startValue4;
       this.startMultiplier4 = startMultiplier4;
       this.startUnit4 = startUnit4;
       this.endCond4 = endCond4;
       this.endValue4 = endValue4;
       this.endMultiplier4 = endMultiplier4;
       this.endUnit4 = endUnit4;
       this.seParametersName5 = seParametersName5;
       this.startCond5 = startCond5;
       this.startValue5 = startValue5;
       this.startMultiplier5 = startMultiplier5;
       this.startUnit5 = startUnit5;
       this.endCond5 = endCond5;
       this.endValue5 = endValue5;
       this.endMultiplier5 = endMultiplier5;
       this.endUnit5 = endUnit5;
       this.featureId1 = featureId1;
       this.featureId2 = featureId2;
       this.featureId3 = featureId3;
       this.featureId4 = featureId4;
       this.featureId5 = featureId5;
       this.plId = plId;
       this.clasId = clasId;
    }
   
    public BigDecimal getId() {
        return this.id;
    }
    
    public void setId(BigDecimal id) {
        this.id = id;
    }
    public String getSeProductLine() {
        return this.seProductLine;
    }
    
    public void setSeProductLine(String seProductLine) {
        this.seProductLine = seProductLine;
    }
    public String getClassName() {
        return this.className;
    }
    
    public void setClassName(String className) {
        this.className = className;
    }
    public String getCodeVersion() {
        return this.codeVersion;
    }
    
    public void setCodeVersion(String codeVersion) {
        this.codeVersion = codeVersion;
    }
    public String getCodeDescription() {
        return this.codeDescription;
    }
    
    public void setCodeDescription(String codeDescription) {
        this.codeDescription = codeDescription;
    }
    public String getRefUrl() {
        return this.refUrl;
    }
    
    public void setRefUrl(String refUrl) {
        this.refUrl = refUrl;
    }
    public BigDecimal getExecutionOrder() {
        return this.executionOrder;
    }
    
    public void setExecutionOrder(BigDecimal executionOrder) {
        this.executionOrder = executionOrder;
    }
    public String getCode() {
        return this.code;
    }
    
    public void setCode(String code) {
        this.code = code;
    }
    public String getSeParametersName1() {
        return this.seParametersName1;
    }
    
    public void setSeParametersName1(String seParametersName1) {
        this.seParametersName1 = seParametersName1;
    }
    public String getStartCond1() {
        return this.startCond1;
    }
    
    public void setStartCond1(String startCond1) {
        this.startCond1 = startCond1;
    }
    public String getStartValue1() {
        return this.startValue1;
    }
    
    public void setStartValue1(String startValue1) {
        this.startValue1 = startValue1;
    }
    public String getStartMultiplier1() {
        return this.startMultiplier1;
    }
    
    public void setStartMultiplier1(String startMultiplier1) {
        this.startMultiplier1 = startMultiplier1;
    }
    public String getStartUnit1() {
        return this.startUnit1;
    }
    
    public void setStartUnit1(String startUnit1) {
        this.startUnit1 = startUnit1;
    }
    public String getEndCond1() {
        return this.endCond1;
    }
    
    public void setEndCond1(String endCond1) {
        this.endCond1 = endCond1;
    }
    public String getEndValue1() {
        return this.endValue1;
    }
    
    public void setEndValue1(String endValue1) {
        this.endValue1 = endValue1;
    }
    public String getEndMultiplier1() {
        return this.endMultiplier1;
    }
    
    public void setEndMultiplier1(String endMultiplier1) {
        this.endMultiplier1 = endMultiplier1;
    }
    public String getEndUnit1() {
        return this.endUnit1;
    }
    
    public void setEndUnit1(String endUnit1) {
        this.endUnit1 = endUnit1;
    }
    public String getSeParametersName2() {
        return this.seParametersName2;
    }
    
    public void setSeParametersName2(String seParametersName2) {
        this.seParametersName2 = seParametersName2;
    }
    public String getStartCond2() {
        return this.startCond2;
    }
    
    public void setStartCond2(String startCond2) {
        this.startCond2 = startCond2;
    }
    public String getStartValue2() {
        return this.startValue2;
    }
    
    public void setStartValue2(String startValue2) {
        this.startValue2 = startValue2;
    }
    public String getStartMultiplier2() {
        return this.startMultiplier2;
    }
    
    public void setStartMultiplier2(String startMultiplier2) {
        this.startMultiplier2 = startMultiplier2;
    }
    public String getStartUnit2() {
        return this.startUnit2;
    }
    
    public void setStartUnit2(String startUnit2) {
        this.startUnit2 = startUnit2;
    }
    public String getEndCond2() {
        return this.endCond2;
    }
    
    public void setEndCond2(String endCond2) {
        this.endCond2 = endCond2;
    }
    public String getEndValue2() {
        return this.endValue2;
    }
    
    public void setEndValue2(String endValue2) {
        this.endValue2 = endValue2;
    }
    public String getEndMultiplier2() {
        return this.endMultiplier2;
    }
    
    public void setEndMultiplier2(String endMultiplier2) {
        this.endMultiplier2 = endMultiplier2;
    }
    public String getEndUnit2() {
        return this.endUnit2;
    }
    
    public void setEndUnit2(String endUnit2) {
        this.endUnit2 = endUnit2;
    }
    public String getSeParametersName3() {
        return this.seParametersName3;
    }
    
    public void setSeParametersName3(String seParametersName3) {
        this.seParametersName3 = seParametersName3;
    }
    public String getStartCond3() {
        return this.startCond3;
    }
    
    public void setStartCond3(String startCond3) {
        this.startCond3 = startCond3;
    }
    public String getStartValue3() {
        return this.startValue3;
    }
    
    public void setStartValue3(String startValue3) {
        this.startValue3 = startValue3;
    }
    public String getStartMultiplier3() {
        return this.startMultiplier3;
    }
    
    public void setStartMultiplier3(String startMultiplier3) {
        this.startMultiplier3 = startMultiplier3;
    }
    public String getStartUnit3() {
        return this.startUnit3;
    }
    
    public void setStartUnit3(String startUnit3) {
        this.startUnit3 = startUnit3;
    }
    public String getEndCond3() {
        return this.endCond3;
    }
    
    public void setEndCond3(String endCond3) {
        this.endCond3 = endCond3;
    }
    public String getEndValue3() {
        return this.endValue3;
    }
    
    public void setEndValue3(String endValue3) {
        this.endValue3 = endValue3;
    }
    public String getEndMultiplier3() {
        return this.endMultiplier3;
    }
    
    public void setEndMultiplier3(String endMultiplier3) {
        this.endMultiplier3 = endMultiplier3;
    }
    public String getEndUnit3() {
        return this.endUnit3;
    }
    
    public void setEndUnit3(String endUnit3) {
        this.endUnit3 = endUnit3;
    }
    public String getSeParametersName4() {
        return this.seParametersName4;
    }
    
    public void setSeParametersName4(String seParametersName4) {
        this.seParametersName4 = seParametersName4;
    }
    public String getStartCond4() {
        return this.startCond4;
    }
    
    public void setStartCond4(String startCond4) {
        this.startCond4 = startCond4;
    }
    public String getStartValue4() {
        return this.startValue4;
    }
    
    public void setStartValue4(String startValue4) {
        this.startValue4 = startValue4;
    }
    public String getStartMultiplier4() {
        return this.startMultiplier4;
    }
    
    public void setStartMultiplier4(String startMultiplier4) {
        this.startMultiplier4 = startMultiplier4;
    }
    public String getStartUnit4() {
        return this.startUnit4;
    }
    
    public void setStartUnit4(String startUnit4) {
        this.startUnit4 = startUnit4;
    }
    public String getEndCond4() {
        return this.endCond4;
    }
    
    public void setEndCond4(String endCond4) {
        this.endCond4 = endCond4;
    }
    public String getEndValue4() {
        return this.endValue4;
    }
    
    public void setEndValue4(String endValue4) {
        this.endValue4 = endValue4;
    }
    public String getEndMultiplier4() {
        return this.endMultiplier4;
    }
    
    public void setEndMultiplier4(String endMultiplier4) {
        this.endMultiplier4 = endMultiplier4;
    }
    public String getEndUnit4() {
        return this.endUnit4;
    }
    
    public void setEndUnit4(String endUnit4) {
        this.endUnit4 = endUnit4;
    }
    public String getSeParametersName5() {
        return this.seParametersName5;
    }
    
    public void setSeParametersName5(String seParametersName5) {
        this.seParametersName5 = seParametersName5;
    }
    public String getStartCond5() {
        return this.startCond5;
    }
    
    public void setStartCond5(String startCond5) {
        this.startCond5 = startCond5;
    }
    public String getStartValue5() {
        return this.startValue5;
    }
    
    public void setStartValue5(String startValue5) {
        this.startValue5 = startValue5;
    }
    public String getStartMultiplier5() {
        return this.startMultiplier5;
    }
    
    public void setStartMultiplier5(String startMultiplier5) {
        this.startMultiplier5 = startMultiplier5;
    }
    public String getStartUnit5() {
        return this.startUnit5;
    }
    
    public void setStartUnit5(String startUnit5) {
        this.startUnit5 = startUnit5;
    }
    public String getEndCond5() {
        return this.endCond5;
    }
    
    public void setEndCond5(String endCond5) {
        this.endCond5 = endCond5;
    }
    public String getEndValue5() {
        return this.endValue5;
    }
    
    public void setEndValue5(String endValue5) {
        this.endValue5 = endValue5;
    }
    public String getEndMultiplier5() {
        return this.endMultiplier5;
    }
    
    public void setEndMultiplier5(String endMultiplier5) {
        this.endMultiplier5 = endMultiplier5;
    }
    public String getEndUnit5() {
        return this.endUnit5;
    }
    
    public void setEndUnit5(String endUnit5) {
        this.endUnit5 = endUnit5;
    }
    public BigDecimal getFeatureId1() {
        return this.featureId1;
    }
    
    public void setFeatureId1(BigDecimal featureId1) {
        this.featureId1 = featureId1;
    }
    public BigDecimal getFeatureId2() {
        return this.featureId2;
    }
    
    public void setFeatureId2(BigDecimal featureId2) {
        this.featureId2 = featureId2;
    }
    public BigDecimal getFeatureId3() {
        return this.featureId3;
    }
    
    public void setFeatureId3(BigDecimal featureId3) {
        this.featureId3 = featureId3;
    }
    public BigDecimal getFeatureId4() {
        return this.featureId4;
    }
    
    public void setFeatureId4(BigDecimal featureId4) {
        this.featureId4 = featureId4;
    }
    public BigDecimal getFeatureId5() {
        return this.featureId5;
    }
    
    public void setFeatureId5(BigDecimal featureId5) {
        this.featureId5 = featureId5;
    }
    public BigDecimal getPlId() {
        return this.plId;
    }
    
    public void setPlId(BigDecimal plId) {
        this.plId = plId;
    }
    public BigDecimal getClasId() {
        return this.clasId;
    }
    
    public void setClasId(BigDecimal clasId) {
        this.clasId = clasId;
    }




}


