package DTOs;
// Generated May 29, 2012 11:19:30 AM by Hibernate Tools 3.2.1.GA


import java.math.BigDecimal;

/**
 * DynamicFlat generated by hbm2java
 */
public class DynamicFlat  implements java.io.Serializable {


     private long comId;
     private XlpSeComponent xlpSeComponent;
     private long manId;
     private long plId;
     private Long fet1;
     private Long fet2;
     private Long fet3;
     private Long fet4;
     private Long fet5;
     private Long fet6;
     private Long fet7;
     private Long fet8;
     private Long fet9;
     private Long fet10;
     private Long fet11;
     private Long fet12;
     private Long fet13;
     private Long fet14;
     private Long fet15;
     private Long fet16;
     private Long fet17;
     private Long fet18;
     private Long fet19;
     private Long fet20;
     private Long fet21;
     private Long fet22;
     private Long fet23;
     private Long fet24;
     private Long fet25;
     private Long fet26;
     private Long fet27;
     private Long fet28;
     private Long fet29;
     private Long fet30;
     private Long fet31;
     private Long fet32;
     private Long fet33;
     private Long fet34;
     private Long fet35;
     private Long fet36;
     private Long fet37;
     private Long fet38;
     private Long fet39;
     private Long fet40;
     private Long fet41;
     private Long fet42;
     private Long fet43;
     private Long fet44;
     private Long fet45;
     private Long fet46;
     private Long fet47;
     private Long fet48;
     private Long fet49;
     private Long fet50;
     private Long fet51;
     private Long fet52;
     private Long fet53;
     private Long fet54;
     private Long fet55;
     private Long fet56;
     private Long fet57;
     private Long fet58;
     private Long fet59;
     private Long fet60;
     private Long fet61;
     private Long fet62;
     private Long fet63;
     private Long fet64;
     private Long fet65;
     private Long fet66;
     private Long fet67;
     private Long fet68;
     private Long fet69;
     private Long fet70;
     private Long fet71;
     private Long fet72;
     private Long fet73;
     private Long fet74;
     private Long fet75;
     private Long fet76;
     private Long fet77;
     private Long fet78;
     private Long fet79;
     private Long fet80;
     private Long fet81;
     private Long fet82;
     private Long fet83;
     private Long fet84;
     private BigDecimal suppPlId;

    public DynamicFlat() {
    }

	
    public DynamicFlat(long comId, XlpSeComponent xlpSeComponent, long manId, long plId) {
        this.comId = comId;
        this.xlpSeComponent = xlpSeComponent;
        this.manId = manId;
        this.plId = plId;
    }
    public DynamicFlat(long comId, XlpSeComponent xlpSeComponent, long manId, long plId, Long fet1, Long fet2, Long fet3, Long fet4, Long fet5, Long fet6, Long fet7, Long fet8, Long fet9, Long fet10, Long fet11, Long fet12, Long fet13, Long fet14, Long fet15, Long fet16, Long fet17, Long fet18, Long fet19, Long fet20, Long fet21, Long fet22, Long fet23, Long fet24, Long fet25, Long fet26, Long fet27, Long fet28, Long fet29, Long fet30, Long fet31, Long fet32, Long fet33, Long fet34, Long fet35, Long fet36, Long fet37, Long fet38, Long fet39, Long fet40, Long fet41, Long fet42, Long fet43, Long fet44, Long fet45, Long fet46, Long fet47, Long fet48, Long fet49, Long fet50, Long fet51, Long fet52, Long fet53, Long fet54, Long fet55, Long fet56, Long fet57, Long fet58, Long fet59, Long fet60, Long fet61, Long fet62, Long fet63, Long fet64, Long fet65, Long fet66, Long fet67, Long fet68, Long fet69, Long fet70, Long fet71, Long fet72, Long fet73, Long fet74, Long fet75, Long fet76, Long fet77, Long fet78, Long fet79, Long fet80, Long fet81, Long fet82, Long fet83, Long fet84, BigDecimal suppPlId) {
       this.comId = comId;
       this.xlpSeComponent = xlpSeComponent;
       this.manId = manId;
       this.plId = plId;
       this.fet1 = fet1;
       this.fet2 = fet2;
       this.fet3 = fet3;
       this.fet4 = fet4;
       this.fet5 = fet5;
       this.fet6 = fet6;
       this.fet7 = fet7;
       this.fet8 = fet8;
       this.fet9 = fet9;
       this.fet10 = fet10;
       this.fet11 = fet11;
       this.fet12 = fet12;
       this.fet13 = fet13;
       this.fet14 = fet14;
       this.fet15 = fet15;
       this.fet16 = fet16;
       this.fet17 = fet17;
       this.fet18 = fet18;
       this.fet19 = fet19;
       this.fet20 = fet20;
       this.fet21 = fet21;
       this.fet22 = fet22;
       this.fet23 = fet23;
       this.fet24 = fet24;
       this.fet25 = fet25;
       this.fet26 = fet26;
       this.fet27 = fet27;
       this.fet28 = fet28;
       this.fet29 = fet29;
       this.fet30 = fet30;
       this.fet31 = fet31;
       this.fet32 = fet32;
       this.fet33 = fet33;
       this.fet34 = fet34;
       this.fet35 = fet35;
       this.fet36 = fet36;
       this.fet37 = fet37;
       this.fet38 = fet38;
       this.fet39 = fet39;
       this.fet40 = fet40;
       this.fet41 = fet41;
       this.fet42 = fet42;
       this.fet43 = fet43;
       this.fet44 = fet44;
       this.fet45 = fet45;
       this.fet46 = fet46;
       this.fet47 = fet47;
       this.fet48 = fet48;
       this.fet49 = fet49;
       this.fet50 = fet50;
       this.fet51 = fet51;
       this.fet52 = fet52;
       this.fet53 = fet53;
       this.fet54 = fet54;
       this.fet55 = fet55;
       this.fet56 = fet56;
       this.fet57 = fet57;
       this.fet58 = fet58;
       this.fet59 = fet59;
       this.fet60 = fet60;
       this.fet61 = fet61;
       this.fet62 = fet62;
       this.fet63 = fet63;
       this.fet64 = fet64;
       this.fet65 = fet65;
       this.fet66 = fet66;
       this.fet67 = fet67;
       this.fet68 = fet68;
       this.fet69 = fet69;
       this.fet70 = fet70;
       this.fet71 = fet71;
       this.fet72 = fet72;
       this.fet73 = fet73;
       this.fet74 = fet74;
       this.fet75 = fet75;
       this.fet76 = fet76;
       this.fet77 = fet77;
       this.fet78 = fet78;
       this.fet79 = fet79;
       this.fet80 = fet80;
       this.fet81 = fet81;
       this.fet82 = fet82;
       this.fet83 = fet83;
       this.fet84 = fet84;
       this.suppPlId = suppPlId;
    }
   
    public long getComId() {
        return this.comId;
    }
    
    public void setComId(long comId) {
        this.comId = comId;
    }
    public XlpSeComponent getXlpSeComponent() {
        return this.xlpSeComponent;
    }
    
    public void setXlpSeComponent(XlpSeComponent xlpSeComponent) {
        this.xlpSeComponent = xlpSeComponent;
    }
    public long getManId() {
        return this.manId;
    }
    
    public void setManId(long manId) {
        this.manId = manId;
    }
    public long getPlId() {
        return this.plId;
    }
    
    public void setPlId(long plId) {
        this.plId = plId;
    }
    public Long getFet1() {
        return this.fet1;
    }
    
    public void setFet1(Long fet1) {
        this.fet1 = fet1;
    }
    public Long getFet2() {
        return this.fet2;
    }
    
    public void setFet2(Long fet2) {
        this.fet2 = fet2;
    }
    public Long getFet3() {
        return this.fet3;
    }
    
    public void setFet3(Long fet3) {
        this.fet3 = fet3;
    }
    public Long getFet4() {
        return this.fet4;
    }
    
    public void setFet4(Long fet4) {
        this.fet4 = fet4;
    }
    public Long getFet5() {
        return this.fet5;
    }
    
    public void setFet5(Long fet5) {
        this.fet5 = fet5;
    }
    public Long getFet6() {
        return this.fet6;
    }
    
    public void setFet6(Long fet6) {
        this.fet6 = fet6;
    }
    public Long getFet7() {
        return this.fet7;
    }
    
    public void setFet7(Long fet7) {
        this.fet7 = fet7;
    }
    public Long getFet8() {
        return this.fet8;
    }
    
    public void setFet8(Long fet8) {
        this.fet8 = fet8;
    }
    public Long getFet9() {
        return this.fet9;
    }
    
    public void setFet9(Long fet9) {
        this.fet9 = fet9;
    }
    public Long getFet10() {
        return this.fet10;
    }
    
    public void setFet10(Long fet10) {
        this.fet10 = fet10;
    }
    public Long getFet11() {
        return this.fet11;
    }
    
    public void setFet11(Long fet11) {
        this.fet11 = fet11;
    }
    public Long getFet12() {
        return this.fet12;
    }
    
    public void setFet12(Long fet12) {
        this.fet12 = fet12;
    }
    public Long getFet13() {
        return this.fet13;
    }
    
    public void setFet13(Long fet13) {
        this.fet13 = fet13;
    }
    public Long getFet14() {
        return this.fet14;
    }
    
    public void setFet14(Long fet14) {
        this.fet14 = fet14;
    }
    public Long getFet15() {
        return this.fet15;
    }
    
    public void setFet15(Long fet15) {
        this.fet15 = fet15;
    }
    public Long getFet16() {
        return this.fet16;
    }
    
    public void setFet16(Long fet16) {
        this.fet16 = fet16;
    }
    public Long getFet17() {
        return this.fet17;
    }
    
    public void setFet17(Long fet17) {
        this.fet17 = fet17;
    }
    public Long getFet18() {
        return this.fet18;
    }
    
    public void setFet18(Long fet18) {
        this.fet18 = fet18;
    }
    public Long getFet19() {
        return this.fet19;
    }
    
    public void setFet19(Long fet19) {
        this.fet19 = fet19;
    }
    public Long getFet20() {
        return this.fet20;
    }
    
    public void setFet20(Long fet20) {
        this.fet20 = fet20;
    }
    public Long getFet21() {
        return this.fet21;
    }
    
    public void setFet21(Long fet21) {
        this.fet21 = fet21;
    }
    public Long getFet22() {
        return this.fet22;
    }
    
    public void setFet22(Long fet22) {
        this.fet22 = fet22;
    }
    public Long getFet23() {
        return this.fet23;
    }
    
    public void setFet23(Long fet23) {
        this.fet23 = fet23;
    }
    public Long getFet24() {
        return this.fet24;
    }
    
    public void setFet24(Long fet24) {
        this.fet24 = fet24;
    }
    public Long getFet25() {
        return this.fet25;
    }
    
    public void setFet25(Long fet25) {
        this.fet25 = fet25;
    }
    public Long getFet26() {
        return this.fet26;
    }
    
    public void setFet26(Long fet26) {
        this.fet26 = fet26;
    }
    public Long getFet27() {
        return this.fet27;
    }
    
    public void setFet27(Long fet27) {
        this.fet27 = fet27;
    }
    public Long getFet28() {
        return this.fet28;
    }
    
    public void setFet28(Long fet28) {
        this.fet28 = fet28;
    }
    public Long getFet29() {
        return this.fet29;
    }
    
    public void setFet29(Long fet29) {
        this.fet29 = fet29;
    }
    public Long getFet30() {
        return this.fet30;
    }
    
    public void setFet30(Long fet30) {
        this.fet30 = fet30;
    }
    public Long getFet31() {
        return this.fet31;
    }
    
    public void setFet31(Long fet31) {
        this.fet31 = fet31;
    }
    public Long getFet32() {
        return this.fet32;
    }
    
    public void setFet32(Long fet32) {
        this.fet32 = fet32;
    }
    public Long getFet33() {
        return this.fet33;
    }
    
    public void setFet33(Long fet33) {
        this.fet33 = fet33;
    }
    public Long getFet34() {
        return this.fet34;
    }
    
    public void setFet34(Long fet34) {
        this.fet34 = fet34;
    }
    public Long getFet35() {
        return this.fet35;
    }
    
    public void setFet35(Long fet35) {
        this.fet35 = fet35;
    }
    public Long getFet36() {
        return this.fet36;
    }
    
    public void setFet36(Long fet36) {
        this.fet36 = fet36;
    }
    public Long getFet37() {
        return this.fet37;
    }
    
    public void setFet37(Long fet37) {
        this.fet37 = fet37;
    }
    public Long getFet38() {
        return this.fet38;
    }
    
    public void setFet38(Long fet38) {
        this.fet38 = fet38;
    }
    public Long getFet39() {
        return this.fet39;
    }
    
    public void setFet39(Long fet39) {
        this.fet39 = fet39;
    }
    public Long getFet40() {
        return this.fet40;
    }
    
    public void setFet40(Long fet40) {
        this.fet40 = fet40;
    }
    public Long getFet41() {
        return this.fet41;
    }
    
    public void setFet41(Long fet41) {
        this.fet41 = fet41;
    }
    public Long getFet42() {
        return this.fet42;
    }
    
    public void setFet42(Long fet42) {
        this.fet42 = fet42;
    }
    public Long getFet43() {
        return this.fet43;
    }
    
    public void setFet43(Long fet43) {
        this.fet43 = fet43;
    }
    public Long getFet44() {
        return this.fet44;
    }
    
    public void setFet44(Long fet44) {
        this.fet44 = fet44;
    }
    public Long getFet45() {
        return this.fet45;
    }
    
    public void setFet45(Long fet45) {
        this.fet45 = fet45;
    }
    public Long getFet46() {
        return this.fet46;
    }
    
    public void setFet46(Long fet46) {
        this.fet46 = fet46;
    }
    public Long getFet47() {
        return this.fet47;
    }
    
    public void setFet47(Long fet47) {
        this.fet47 = fet47;
    }
    public Long getFet48() {
        return this.fet48;
    }
    
    public void setFet48(Long fet48) {
        this.fet48 = fet48;
    }
    public Long getFet49() {
        return this.fet49;
    }
    
    public void setFet49(Long fet49) {
        this.fet49 = fet49;
    }
    public Long getFet50() {
        return this.fet50;
    }
    
    public void setFet50(Long fet50) {
        this.fet50 = fet50;
    }
    public Long getFet51() {
        return this.fet51;
    }
    
    public void setFet51(Long fet51) {
        this.fet51 = fet51;
    }
    public Long getFet52() {
        return this.fet52;
    }
    
    public void setFet52(Long fet52) {
        this.fet52 = fet52;
    }
    public Long getFet53() {
        return this.fet53;
    }
    
    public void setFet53(Long fet53) {
        this.fet53 = fet53;
    }
    public Long getFet54() {
        return this.fet54;
    }
    
    public void setFet54(Long fet54) {
        this.fet54 = fet54;
    }
    public Long getFet55() {
        return this.fet55;
    }
    
    public void setFet55(Long fet55) {
        this.fet55 = fet55;
    }
    public Long getFet56() {
        return this.fet56;
    }
    
    public void setFet56(Long fet56) {
        this.fet56 = fet56;
    }
    public Long getFet57() {
        return this.fet57;
    }
    
    public void setFet57(Long fet57) {
        this.fet57 = fet57;
    }
    public Long getFet58() {
        return this.fet58;
    }
    
    public void setFet58(Long fet58) {
        this.fet58 = fet58;
    }
    public Long getFet59() {
        return this.fet59;
    }
    
    public void setFet59(Long fet59) {
        this.fet59 = fet59;
    }
    public Long getFet60() {
        return this.fet60;
    }
    
    public void setFet60(Long fet60) {
        this.fet60 = fet60;
    }
    public Long getFet61() {
        return this.fet61;
    }
    
    public void setFet61(Long fet61) {
        this.fet61 = fet61;
    }
    public Long getFet62() {
        return this.fet62;
    }
    
    public void setFet62(Long fet62) {
        this.fet62 = fet62;
    }
    public Long getFet63() {
        return this.fet63;
    }
    
    public void setFet63(Long fet63) {
        this.fet63 = fet63;
    }
    public Long getFet64() {
        return this.fet64;
    }
    
    public void setFet64(Long fet64) {
        this.fet64 = fet64;
    }
    public Long getFet65() {
        return this.fet65;
    }
    
    public void setFet65(Long fet65) {
        this.fet65 = fet65;
    }
    public Long getFet66() {
        return this.fet66;
    }
    
    public void setFet66(Long fet66) {
        this.fet66 = fet66;
    }
    public Long getFet67() {
        return this.fet67;
    }
    
    public void setFet67(Long fet67) {
        this.fet67 = fet67;
    }
    public Long getFet68() {
        return this.fet68;
    }
    
    public void setFet68(Long fet68) {
        this.fet68 = fet68;
    }
    public Long getFet69() {
        return this.fet69;
    }
    
    public void setFet69(Long fet69) {
        this.fet69 = fet69;
    }
    public Long getFet70() {
        return this.fet70;
    }
    
    public void setFet70(Long fet70) {
        this.fet70 = fet70;
    }
    public Long getFet71() {
        return this.fet71;
    }
    
    public void setFet71(Long fet71) {
        this.fet71 = fet71;
    }
    public Long getFet72() {
        return this.fet72;
    }
    
    public void setFet72(Long fet72) {
        this.fet72 = fet72;
    }
    public Long getFet73() {
        return this.fet73;
    }
    
    public void setFet73(Long fet73) {
        this.fet73 = fet73;
    }
    public Long getFet74() {
        return this.fet74;
    }
    
    public void setFet74(Long fet74) {
        this.fet74 = fet74;
    }
    public Long getFet75() {
        return this.fet75;
    }
    
    public void setFet75(Long fet75) {
        this.fet75 = fet75;
    }
    public Long getFet76() {
        return this.fet76;
    }
    
    public void setFet76(Long fet76) {
        this.fet76 = fet76;
    }
    public Long getFet77() {
        return this.fet77;
    }
    
    public void setFet77(Long fet77) {
        this.fet77 = fet77;
    }
    public Long getFet78() {
        return this.fet78;
    }
    
    public void setFet78(Long fet78) {
        this.fet78 = fet78;
    }
    public Long getFet79() {
        return this.fet79;
    }
    
    public void setFet79(Long fet79) {
        this.fet79 = fet79;
    }
    public Long getFet80() {
        return this.fet80;
    }
    
    public void setFet80(Long fet80) {
        this.fet80 = fet80;
    }
    public Long getFet81() {
        return this.fet81;
    }
    
    public void setFet81(Long fet81) {
        this.fet81 = fet81;
    }
    public Long getFet82() {
        return this.fet82;
    }
    
    public void setFet82(Long fet82) {
        this.fet82 = fet82;
    }
    public Long getFet83() {
        return this.fet83;
    }
    
    public void setFet83(Long fet83) {
        this.fet83 = fet83;
    }
    public Long getFet84() {
        return this.fet84;
    }
    
    public void setFet84(Long fet84) {
        this.fet84 = fet84;
    }
    public BigDecimal getSuppPlId() {
        return this.suppPlId;
    }
    
    public void setSuppPlId(BigDecimal suppPlId) {
        this.suppPlId = suppPlId;
    }




}


