package DTOs;
// Generated May 29, 2012 11:19:30 AM by Hibernate Tools 3.2.1.GA



import java.math.BigDecimal;

/**
 * ShFeature generated by hbm2java
 */
public class ShFeature  implements java.io.Serializable {
	
     private long id;
     private String fetName;
     private String fetValue;
     private BigDecimal valueId;
     private BigDecimal fetId;
     private String type;
     private String colName;
     private String unit;
     private String multiplier;
     private String ip;

    public String getIp() {
		return ip;
	}


	public void setIp(String ip) {
		this.ip = ip;
	}


	public ShFeature() {
    }

	
    public ShFeature(long id) {
        this.id = id;
    }
    public ShFeature(long id, String fetName, String fetValue, BigDecimal valueId, BigDecimal fetId, String type, String colName, String unit, String multiplier) {
       this.id = id;
       this.fetName = fetName;
       this.fetValue = fetValue;
       this.valueId = valueId;
       this.fetId = fetId;
       this.type = type;
       this.colName = colName;
       this.unit = unit;
       this.multiplier = multiplier;
    }
   
    public long getId() {
        return this.id;
    }
    
    public void setId(long id) {
        this.id = id;
    }
    public String getFetName() {
        return this.fetName;
    }
    
    public void setFetName(String fetName) {
        this.fetName = fetName;
    }
    public String getFetValue() {
        return this.fetValue;
    }
    
    public void setFetValue(String fetValue) {
        this.fetValue = fetValue;
    }
    public BigDecimal getValueId() {
        return this.valueId;
    }
    
    public void setValueId(BigDecimal valueId) {
        this.valueId = valueId;
    }
    public BigDecimal getFetId() {
        return this.fetId;
    }
    
    public void setFetId(BigDecimal fetId) {
        this.fetId = fetId;
    }
    public String getType() {
        return this.type;
    }
    
    public void setType(String type) {
        this.type = type;
    }
    public String getColName() {
        return this.colName;
    }
    
    public void setColName(String colName) {
        this.colName = colName;
    }
    public String getUnit() {
        return this.unit;
    }
    
    public void setUnit(String unit) {
        this.unit = unit;
    }
    public String getMultiplier() {
        return this.multiplier;
    }
    
    public void setMultiplier(String multiplier) {
        this.multiplier = multiplier;
    }

}


