package DTOs;
// Generated May 29, 2012 11:19:30 AM by Hibernate Tools 3.2.1.GA


import java.math.BigDecimal;
import java.util.Date;

/**
 * TblQchApprovedValues generated by hbm2java
 */
public class TblQchApprovedValues  implements java.io.Serializable {


     private BigDecimal valueId;
     private XlpSePl xlpSePl;
     private XlpSeFeature xlpSeFeature;
     private String plName;
     private String fetName;
     private String fetValue;
     private BigDecimal flag;
     private Date insrtDate;
     private Date updateDate;
     private String sign;
     private String value;
     private String type;
     private String condition;
     private String multiplier;
     private String unit;
     private BigDecimal dispOrder;
     private String valueType;

    public TblQchApprovedValues() {
    }

	
    public TblQchApprovedValues(BigDecimal valueId, String value) {
        this.valueId = valueId;
        this.value = value;
    }
    public TblQchApprovedValues(BigDecimal valueId, XlpSePl xlpSePl, XlpSeFeature xlpSeFeature, String plName, String fetName, String fetValue, BigDecimal flag, Date insrtDate, Date updateDate, String sign, String value, String type, String condition, String multiplier, String unit, BigDecimal dispOrder, String valueType) {
       this.valueId = valueId;
       this.xlpSePl = xlpSePl;
       this.xlpSeFeature = xlpSeFeature;
       this.plName = plName;
       this.fetName = fetName;
       this.fetValue = fetValue;
       this.flag = flag;
       this.insrtDate = insrtDate;
       this.updateDate = updateDate;
       this.sign = sign;
       this.value = value;
       this.type = type;
       this.condition = condition;
       this.multiplier = multiplier;
       this.unit = unit;
       this.dispOrder = dispOrder;
       this.valueType = valueType;
    }
   
    public BigDecimal getValueId() {
        return this.valueId;
    }
    
    public void setValueId(BigDecimal valueId) {
        this.valueId = valueId;
    }
    public XlpSePl getXlpSePl() {
        return this.xlpSePl;
    }
    
    public void setXlpSePl(XlpSePl xlpSePl) {
        this.xlpSePl = xlpSePl;
    }
    public XlpSeFeature getXlpSeFeature() {
        return this.xlpSeFeature;
    }
    
    public void setXlpSeFeature(XlpSeFeature xlpSeFeature) {
        this.xlpSeFeature = xlpSeFeature;
    }
    public String getPlName() {
        return this.plName;
    }
    
    public void setPlName(String plName) {
        this.plName = plName;
    }
    public String getFetName() {
        return this.fetName;
    }
    
    public void setFetName(String fetName) {
        this.fetName = fetName;
    }
    public String getFetValue() {
        return this.fetValue;
    }
    
    public void setFetValue(String fetValue) {
        this.fetValue = fetValue;
    }
    public BigDecimal getFlag() {
        return this.flag;
    }
    
    public void setFlag(BigDecimal flag) {
        this.flag = flag;
    }
    public Date getInsrtDate() {
        return this.insrtDate;
    }
    
    public void setInsrtDate(Date insrtDate) {
        this.insrtDate = insrtDate;
    }
    public Date getUpdateDate() {
        return this.updateDate;
    }
    
    public void setUpdateDate(Date updateDate) {
        this.updateDate = updateDate;
    }
    public String getSign() {
        return this.sign;
    }
    
    public void setSign(String sign) {
        this.sign = sign;
    }
    public String getValue() {
        return this.value;
    }
    
    public void setValue(String value) {
        this.value = value;
    }
    public String getType() {
        return this.type;
    }
    
    public void setType(String type) {
        this.type = type;
    }
    public String getCondition() {
        return this.condition;
    }
    
    public void setCondition(String condition) {
        this.condition = condition;
    }
    public String getMultiplier() {
        return this.multiplier;
    }
    
    public void setMultiplier(String multiplier) {
        this.multiplier = multiplier;
    }
    public String getUnit() {
        return this.unit;
    }
    
    public void setUnit(String unit) {
        this.unit = unit;
    }
    public BigDecimal getDispOrder() {
        return this.dispOrder;
    }
    
    public void setDispOrder(BigDecimal dispOrder) {
        this.dispOrder = dispOrder;
    }
    public String getValueType() {
        return this.valueType;
    }
    
    public void setValueType(String valueType) {
        this.valueType = valueType;
    }




}


