package DTOs;
// Generated May 29, 2012 11:19:30 AM by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;

/**
 * XlpSeParenthier generated by hbm2java
 */
public class XlpSeParenthier  implements java.io.Serializable {


     private long phrId;
     private XlpSePl xlpSePl;
     private short phrOrder;
     private String phrName;
     private Set xlpSeFeatures = new HashSet(0);

    public XlpSeParenthier() {
    }

	
    public XlpSeParenthier(long phrId, XlpSePl xlpSePl, short phrOrder, String phrName) {
        this.phrId = phrId;
        this.xlpSePl = xlpSePl;
        this.phrOrder = phrOrder;
        this.phrName = phrName;
    }
    public XlpSeParenthier(long phrId, XlpSePl xlpSePl, short phrOrder, String phrName, Set xlpSeFeatures) {
       this.phrId = phrId;
       this.xlpSePl = xlpSePl;
       this.phrOrder = phrOrder;
       this.phrName = phrName;
       this.xlpSeFeatures = xlpSeFeatures;
    }
   
    public long getPhrId() {
        return this.phrId;
    }
    
    public void setPhrId(long phrId) {
        this.phrId = phrId;
    }
    public XlpSePl getXlpSePl() {
        return this.xlpSePl;
    }
    
    public void setXlpSePl(XlpSePl xlpSePl) {
        this.xlpSePl = xlpSePl;
    }
    public short getPhrOrder() {
        return this.phrOrder;
    }
    
    public void setPhrOrder(short phrOrder) {
        this.phrOrder = phrOrder;
    }
    public String getPhrName() {
        return this.phrName;
    }
    
    public void setPhrName(String phrName) {
        this.phrName = phrName;
    }
    public Set getXlpSeFeatures() {
        return this.xlpSeFeatures;
    }
    
    public void setXlpSeFeatures(Set xlpSeFeatures) {
        this.xlpSeFeatures = xlpSeFeatures;
    }




}


