package DTOs;
// Generated May 29, 2012 11:19:30 AM by Hibernate Tools 3.2.1.GA


import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;

/**
 * XlpSeFeature generated by hbm2java
 */
public class XlpSeFeature  implements java.io.Serializable {


     private long fetId;
     private XlpSeParenthier xlpSeParenthier;
     private XlpSePl xlpSePl;
     private String fetName;
     private Boolean fetType;
     private String fetLength;
     private boolean fetSearchableFlag;
     private String fetSort;
     private String fetPresentation;
     private Short fetPhierlocalorder;
     private short fetExpertsheetorder;
     private String fetUnit;
     private boolean fetSheetviewFlag;
     private Long fetCoreId;
     private boolean fetMv;
     private String colNm;
     private String sortType;
     private BigDecimal additionalfetFlg;
     private BigDecimal columnfetFlg;
     private String featureSymbol;
     private String featureDefinition;
     private boolean pkgFlag;
     private Set tblQchApprovedValueses = new HashSet(0);

    public XlpSeFeature() {
    }

	
    public XlpSeFeature(long fetId, XlpSePl xlpSePl, String fetName, String fetLength, boolean fetSearchableFlag, short fetExpertsheetorder, boolean fetSheetviewFlag, boolean fetMv, boolean pkgFlag) {
        this.fetId = fetId;
        this.xlpSePl = xlpSePl;
        this.fetName = fetName;
        this.fetLength = fetLength;
        this.fetSearchableFlag = fetSearchableFlag;
        this.fetExpertsheetorder = fetExpertsheetorder;
        this.fetSheetviewFlag = fetSheetviewFlag;
        this.fetMv = fetMv;
        this.pkgFlag = pkgFlag;
    }
    public XlpSeFeature(long fetId, XlpSeParenthier xlpSeParenthier, XlpSePl xlpSePl, String fetName, Boolean fetType, String fetLength, boolean fetSearchableFlag, String fetSort, String fetPresentation, Short fetPhierlocalorder, short fetExpertsheetorder, String fetUnit, boolean fetSheetviewFlag, Long fetCoreId, boolean fetMv, String colNm, String sortType, BigDecimal additionalfetFlg, BigDecimal columnfetFlg, String featureSymbol, String featureDefinition, boolean pkgFlag, Set tblQchApprovedValueses) {
       this.fetId = fetId;
       this.xlpSeParenthier = xlpSeParenthier;
       this.xlpSePl = xlpSePl;
       this.fetName = fetName;
       this.fetType = fetType;
       this.fetLength = fetLength;
       this.fetSearchableFlag = fetSearchableFlag;
       this.fetSort = fetSort;
       this.fetPresentation = fetPresentation;
       this.fetPhierlocalorder = fetPhierlocalorder;
       this.fetExpertsheetorder = fetExpertsheetorder;
       this.fetUnit = fetUnit;
       this.fetSheetviewFlag = fetSheetviewFlag;
       this.fetCoreId = fetCoreId;
       this.fetMv = fetMv;
       this.colNm = colNm;
       this.sortType = sortType;
       this.additionalfetFlg = additionalfetFlg;
       this.columnfetFlg = columnfetFlg;
       this.featureSymbol = featureSymbol;
       this.featureDefinition = featureDefinition;
       this.pkgFlag = pkgFlag;
       this.tblQchApprovedValueses = tblQchApprovedValueses;
    }
   
    public long getFetId() {
        return this.fetId;
    }
    
    public void setFetId(long fetId) {
        this.fetId = fetId;
    }
    public XlpSeParenthier getXlpSeParenthier() {
        return this.xlpSeParenthier;
    }
    
    public void setXlpSeParenthier(XlpSeParenthier xlpSeParenthier) {
        this.xlpSeParenthier = xlpSeParenthier;
    }
    public XlpSePl getXlpSePl() {
        return this.xlpSePl;
    }
    
    public void setXlpSePl(XlpSePl xlpSePl) {
        this.xlpSePl = xlpSePl;
    }
    public String getFetName() {
        return this.fetName;
    }
    
    public void setFetName(String fetName) {
        this.fetName = fetName;
    }
    public Boolean getFetType() {
        return this.fetType;
    }
    
    public void setFetType(Boolean fetType) {
        this.fetType = fetType;
    }
    public String getFetLength() {
        return this.fetLength;
    }
    
    public void setFetLength(String fetLength) {
        this.fetLength = fetLength;
    }
    public boolean isFetSearchableFlag() {
        return this.fetSearchableFlag;
    }
    
    public void setFetSearchableFlag(boolean fetSearchableFlag) {
        this.fetSearchableFlag = fetSearchableFlag;
    }
    public String getFetSort() {
        return this.fetSort;
    }
    
    public void setFetSort(String fetSort) {
        this.fetSort = fetSort;
    }
    public String getFetPresentation() {
        return this.fetPresentation;
    }
    
    public void setFetPresentation(String fetPresentation) {
        this.fetPresentation = fetPresentation;
    }
    public Short getFetPhierlocalorder() {
        return this.fetPhierlocalorder;
    }
    
    public void setFetPhierlocalorder(Short fetPhierlocalorder) {
        this.fetPhierlocalorder = fetPhierlocalorder;
    }
    public short getFetExpertsheetorder() {
        return this.fetExpertsheetorder;
    }
    
    public void setFetExpertsheetorder(short fetExpertsheetorder) {
        this.fetExpertsheetorder = fetExpertsheetorder;
    }
    public String getFetUnit() {
        return this.fetUnit;
    }
    
    public void setFetUnit(String fetUnit) {
        this.fetUnit = fetUnit;
    }
    public boolean isFetSheetviewFlag() {
        return this.fetSheetviewFlag;
    }
    
    public void setFetSheetviewFlag(boolean fetSheetviewFlag) {
        this.fetSheetviewFlag = fetSheetviewFlag;
    }
    public Long getFetCoreId() {
        return this.fetCoreId;
    }
    
    public void setFetCoreId(Long fetCoreId) {
        this.fetCoreId = fetCoreId;
    }
    public boolean isFetMv() {
        return this.fetMv;
    }
    
    public void setFetMv(boolean fetMv) {
        this.fetMv = fetMv;
    }
    public String getColNm() {
        return this.colNm;
    }
    
    public void setColNm(String colNm) {
        this.colNm = colNm;
    }
    public String getSortType() {
        return this.sortType;
    }
    
    public void setSortType(String sortType) {
        this.sortType = sortType;
    }
    public BigDecimal getAdditionalfetFlg() {
        return this.additionalfetFlg;
    }
    
    public void setAdditionalfetFlg(BigDecimal additionalfetFlg) {
        this.additionalfetFlg = additionalfetFlg;
    }
    public BigDecimal getColumnfetFlg() {
        return this.columnfetFlg;
    }
    
    public void setColumnfetFlg(BigDecimal columnfetFlg) {
        this.columnfetFlg = columnfetFlg;
    }
    public String getFeatureSymbol() {
        return this.featureSymbol;
    }
    
    public void setFeatureSymbol(String featureSymbol) {
        this.featureSymbol = featureSymbol;
    }
    public String getFeatureDefinition() {
        return this.featureDefinition;
    }
    
    public void setFeatureDefinition(String featureDefinition) {
        this.featureDefinition = featureDefinition;
    }
    public boolean isPkgFlag() {
        return this.pkgFlag;
    }
    
    public void setPkgFlag(boolean pkgFlag) {
        this.pkgFlag = pkgFlag;
    }
    public Set getTblQchApprovedValueses() {
        return this.tblQchApprovedValueses;
    }
    
    public void setTblQchApprovedValueses(Set tblQchApprovedValueses) {
        this.tblQchApprovedValueses = tblQchApprovedValueses;
    }




}


