package DTOs;
// Generated May 29, 2012 11:19:30 AM by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;

/**
 * XlpSePl generated by hbm2java
 */
public class XlpSePl  implements java.io.Serializable {


     private long plId;
     private XlpSeTaxonomy xlpSeTaxonomy;
     private String plName;
     private boolean plType;
     private long plCreationDate;
     private String crossFlag;
     private String isBatt;
     private Set xlpSeComponents = new HashSet(0);
     private Set tblQchApprovedValueses = new HashSet(0);
     private Set xlpSeFeatures = new HashSet(0);
     private Set xlpSeParenthiers = new HashSet(0);

    public XlpSePl() {
    }

	
    public XlpSePl(long plId, String plName, boolean plType, long plCreationDate) {
        this.plId = plId;
        this.plName = plName;
        this.plType = plType;
        this.plCreationDate = plCreationDate;
    }
    public XlpSePl(long plId, XlpSeTaxonomy xlpSeTaxonomy, String plName, boolean plType, long plCreationDate, String crossFlag, String isBatt, Set xlpSeComponents, Set tblQchApprovedValueses, Set xlpSeFeatures, Set xlpSeParenthiers) {
       this.plId = plId;
       this.xlpSeTaxonomy = xlpSeTaxonomy;
       this.plName = plName;
       this.plType = plType;
       this.plCreationDate = plCreationDate;
       this.crossFlag = crossFlag;
       this.isBatt = isBatt;
       this.xlpSeComponents = xlpSeComponents;
       this.tblQchApprovedValueses = tblQchApprovedValueses;
       this.xlpSeFeatures = xlpSeFeatures;
       this.xlpSeParenthiers = xlpSeParenthiers;
    }
   
    public long getPlId() {
        return this.plId;
    }
    
    public void setPlId(long plId) {
        this.plId = plId;
    }
    public XlpSeTaxonomy getXlpSeTaxonomy() {
        return this.xlpSeTaxonomy;
    }
    
    public void setXlpSeTaxonomy(XlpSeTaxonomy xlpSeTaxonomy) {
        this.xlpSeTaxonomy = xlpSeTaxonomy;
    }
    public String getPlName() {
        return this.plName;
    }
    
    public void setPlName(String plName) {
        this.plName = plName;
    }
    public boolean isPlType() {
        return this.plType;
    }
    
    public void setPlType(boolean plType) {
        this.plType = plType;
    }
    public long getPlCreationDate() {
        return this.plCreationDate;
    }
    
    public void setPlCreationDate(long plCreationDate) {
        this.plCreationDate = plCreationDate;
    }
    public String getCrossFlag() {
        return this.crossFlag;
    }
    
    public void setCrossFlag(String crossFlag) {
        this.crossFlag = crossFlag;
    }
    public String getIsBatt() {
        return this.isBatt;
    }
    
    public void setIsBatt(String isBatt) {
        this.isBatt = isBatt;
    }
    public Set getXlpSeComponents() {
        return this.xlpSeComponents;
    }
    
    public void setXlpSeComponents(Set xlpSeComponents) {
        this.xlpSeComponents = xlpSeComponents;
    }
    public Set getTblQchApprovedValueses() {
        return this.tblQchApprovedValueses;
    }
    
    public void setTblQchApprovedValueses(Set tblQchApprovedValueses) {
        this.tblQchApprovedValueses = tblQchApprovedValueses;
    }
    public Set getXlpSeFeatures() {
        return this.xlpSeFeatures;
    }
    
    public void setXlpSeFeatures(Set xlpSeFeatures) {
        this.xlpSeFeatures = xlpSeFeatures;
    }
    public Set getXlpSeParenthiers() {
        return this.xlpSeParenthiers;
    }
    
    public void setXlpSeParenthiers(Set xlpSeParenthiers) {
        this.xlpSeParenthiers = xlpSeParenthiers;
    }




}


