package DTOs;
// Generated May 29, 2012 11:19:30 AM by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;

/**
 * XlpSeTaxonomy generated by hbm2java
 */
public class XlpSeTaxonomy  implements java.io.Serializable {


     private long taxId;
     private XlpSeTaxonomy xlpSeTaxonomy;
     private String taxName;
     private String taxPath;
     private Set xlpSePls = new HashSet(0);
     private Set xlpSeTaxonomies = new HashSet(0);

    public XlpSeTaxonomy() {
    }

	
    public XlpSeTaxonomy(long taxId, String taxName, String taxPath) {
        this.taxId = taxId;
        this.taxName = taxName;
        this.taxPath = taxPath;
    }
    public XlpSeTaxonomy(long taxId, XlpSeTaxonomy xlpSeTaxonomy, String taxName, String taxPath, Set xlpSePls, Set xlpSeTaxonomies) {
       this.taxId = taxId;
       this.xlpSeTaxonomy = xlpSeTaxonomy;
       this.taxName = taxName;
       this.taxPath = taxPath;
       this.xlpSePls = xlpSePls;
       this.xlpSeTaxonomies = xlpSeTaxonomies;
    }
   
    public long getTaxId() {
        return this.taxId;
    }
    
    public void setTaxId(long taxId) {
        this.taxId = taxId;
    }
    public XlpSeTaxonomy getXlpSeTaxonomy() {
        return this.xlpSeTaxonomy;
    }
    
    public void setXlpSeTaxonomy(XlpSeTaxonomy xlpSeTaxonomy) {
        this.xlpSeTaxonomy = xlpSeTaxonomy;
    }
    public String getTaxName() {
        return this.taxName;
    }
    
    public void setTaxName(String taxName) {
        this.taxName = taxName;
    }
    public String getTaxPath() {
        return this.taxPath;
    }
    
    public void setTaxPath(String taxPath) {
        this.taxPath = taxPath;
    }
    public Set getXlpSePls() {
        return this.xlpSePls;
    }
    
    public void setXlpSePls(Set xlpSePls) {
        this.xlpSePls = xlpSePls;
    }
    public Set getXlpSeTaxonomies() {
        return this.xlpSeTaxonomies;
    }
    
    public void setXlpSeTaxonomies(Set xlpSeTaxonomies) {
        this.xlpSeTaxonomies = xlpSeTaxonomies;
    }




}


