package DTOs;
// Generated May 29, 2012 11:19:30 AM by Hibernate Tools 3.2.1.GA


import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;

/**
 * XlpSeComponent generated by hbm2java
 */
public class XlpSeComponent  implements java.io.Serializable {


     private long comId;
     private TblMapFam tblMapFam;
     private TblMapGen tblMapGen;
     private XlpSeManufacturer xlpSeManufacturerByOrgManId;
     private XlpSeManufacturer xlpSeManufacturerByManId;
     private XlpSePl xlpSePl;
     private XlpSeFamily xlpSeFamily;
     private MessageAdmin messageAdmin;
     private String comPartnum;
     private String comDesc;
     private Long comReleaseDate;
     private long comLastupdateDate;
     private String nanPartnum;
     private BigDecimal pkgId;
     private BigDecimal pdfId;
     private String lcState;
     private String rohs;
     private String lcDate;
     private String poKey;
     private BigDecimal militaryFlag;
     private Set dynamicFlats = new HashSet(0);

    public XlpSeComponent() {
    }

	
    public XlpSeComponent(long comId, XlpSeManufacturer xlpSeManufacturerByManId, XlpSePl xlpSePl, String comPartnum, String comDesc, long comLastupdateDate) {
        this.comId = comId;
        this.xlpSeManufacturerByManId = xlpSeManufacturerByManId;
        this.xlpSePl = xlpSePl;
        this.comPartnum = comPartnum;
        this.comDesc = comDesc;
        this.comLastupdateDate = comLastupdateDate;
    }
    public XlpSeComponent(long comId, TblMapFam tblMapFam, TblMapGen tblMapGen, XlpSeManufacturer xlpSeManufacturerByOrgManId, XlpSeManufacturer xlpSeManufacturerByManId, XlpSePl xlpSePl, XlpSeFamily xlpSeFamily, MessageAdmin messageAdmin, String comPartnum, String comDesc, Long comReleaseDate, long comLastupdateDate, String nanPartnum, BigDecimal pkgId, BigDecimal pdfId, String lcState, String rohs, String lcDate, String poKey, BigDecimal militaryFlag, Set dynamicFlats) {
       this.comId = comId;
       this.tblMapFam = tblMapFam;
       this.tblMapGen = tblMapGen;
       this.xlpSeManufacturerByOrgManId = xlpSeManufacturerByOrgManId;
       this.xlpSeManufacturerByManId = xlpSeManufacturerByManId;
       this.xlpSePl = xlpSePl;
       this.xlpSeFamily = xlpSeFamily;
       this.messageAdmin = messageAdmin;
       this.comPartnum = comPartnum;
       this.comDesc = comDesc;
       this.comReleaseDate = comReleaseDate;
       this.comLastupdateDate = comLastupdateDate;
       this.nanPartnum = nanPartnum;
       this.pkgId = pkgId;
       this.pdfId = pdfId;
       this.lcState = lcState;
       this.rohs = rohs;
       this.lcDate = lcDate;
       this.poKey = poKey;
       this.militaryFlag = militaryFlag;
       this.dynamicFlats = dynamicFlats;
    }
   
    public long getComId() {
        return this.comId;
    }
    
    public void setComId(long comId) {
        this.comId = comId;
    }
    public TblMapFam getTblMapFam() {
        return this.tblMapFam;
    }
    
    public void setTblMapFam(TblMapFam tblMapFam) {
        this.tblMapFam = tblMapFam;
    }
    public TblMapGen getTblMapGen() {
        return this.tblMapGen;
    }
    
    public void setTblMapGen(TblMapGen tblMapGen) {
        this.tblMapGen = tblMapGen;
    }
    public XlpSeManufacturer getXlpSeManufacturerByOrgManId() {
        return this.xlpSeManufacturerByOrgManId;
    }
    
    public void setXlpSeManufacturerByOrgManId(XlpSeManufacturer xlpSeManufacturerByOrgManId) {
        this.xlpSeManufacturerByOrgManId = xlpSeManufacturerByOrgManId;
    }
    public XlpSeManufacturer getXlpSeManufacturerByManId() {
        return this.xlpSeManufacturerByManId;
    }
    
    public void setXlpSeManufacturerByManId(XlpSeManufacturer xlpSeManufacturerByManId) {
        this.xlpSeManufacturerByManId = xlpSeManufacturerByManId;
    }
    public XlpSePl getXlpSePl() {
        return this.xlpSePl;
    }
    
    public void setXlpSePl(XlpSePl xlpSePl) {
        this.xlpSePl = xlpSePl;
    }
    public XlpSeFamily getXlpSeFamily() {
        return this.xlpSeFamily;
    }
    
    public void setXlpSeFamily(XlpSeFamily xlpSeFamily) {
        this.xlpSeFamily = xlpSeFamily;
    }
    public MessageAdmin getMessageAdmin() {
        return this.messageAdmin;
    }
    
    public void setMessageAdmin(MessageAdmin messageAdmin) {
        this.messageAdmin = messageAdmin;
    }
    public String getComPartnum() {
        return this.comPartnum;
    }
    
    public void setComPartnum(String comPartnum) {
        this.comPartnum = comPartnum;
    }
    public String getComDesc() {
        return this.comDesc;
    }
    
    public void setComDesc(String comDesc) {
        this.comDesc = comDesc;
    }
    public Long getComReleaseDate() {
        return this.comReleaseDate;
    }
    
    public void setComReleaseDate(Long comReleaseDate) {
        this.comReleaseDate = comReleaseDate;
    }
    public long getComLastupdateDate() {
        return this.comLastupdateDate;
    }
    
    public void setComLastupdateDate(long comLastupdateDate) {
        this.comLastupdateDate = comLastupdateDate;
    }
    public String getNanPartnum() {
        return this.nanPartnum;
    }
    
    public void setNanPartnum(String nanPartnum) {
        this.nanPartnum = nanPartnum;
    }
    public BigDecimal getPkgId() {
        return this.pkgId;
    }
    
    public void setPkgId(BigDecimal pkgId) {
        this.pkgId = pkgId;
    }
    public BigDecimal getPdfId() {
        return this.pdfId;
    }
    
    public void setPdfId(BigDecimal pdfId) {
        this.pdfId = pdfId;
    }
    public String getLcState() {
        return this.lcState;
    }
    
    public void setLcState(String lcState) {
        this.lcState = lcState;
    }
    public String getRohs() {
        return this.rohs;
    }
    
    public void setRohs(String rohs) {
        this.rohs = rohs;
    }
    public String getLcDate() {
        return this.lcDate;
    }
    
    public void setLcDate(String lcDate) {
        this.lcDate = lcDate;
    }
    public String getPoKey() {
        return this.poKey;
    }
    
    public void setPoKey(String poKey) {
        this.poKey = poKey;
    }
    public BigDecimal getMilitaryFlag() {
        return this.militaryFlag;
    }
    
    public void setMilitaryFlag(BigDecimal militaryFlag) {
        this.militaryFlag = militaryFlag;
    }
    public Set getDynamicFlats() {
        return this.dynamicFlats;
    }
    
    public void setDynamicFlats(Set dynamicFlats) {
        this.dynamicFlats = dynamicFlats;
    }




}


