package DTOs;
// Generated May 29, 2012 11:19:30 AM by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;

/**
 * XlpSeManufacturer generated by hbm2java
 */
public class XlpSeManufacturer  implements java.io.Serializable {


     private long manId;
     private String manName;
     private String manCode;
     private String manSiteUrl;
     private String manLogoUrl;
     private String manComment;
     private String contact;
     private String roadmapUrl;
     private String chemicalUrl;
     private String packageUrl;
     private Boolean chineese;
     private Boolean key;
     private Set xlpSeComponentsForManId = new HashSet(0);
     private Set xlpSeComponentsForOrgManId = new HashSet(0);

    public XlpSeManufacturer() {
    }

	
    public XlpSeManufacturer(long manId, String manName, String manCode) {
        this.manId = manId;
        this.manName = manName;
        this.manCode = manCode;
    }
    public XlpSeManufacturer(long manId, String manName, String manCode, String manSiteUrl, String manLogoUrl, String manComment, String contact, String roadmapUrl, String chemicalUrl, String packageUrl, Boolean chineese, Boolean key, Set xlpSeComponentsForManId, Set xlpSeComponentsForOrgManId) {
       this.manId = manId;
       this.manName = manName;
       this.manCode = manCode;
       this.manSiteUrl = manSiteUrl;
       this.manLogoUrl = manLogoUrl;
       this.manComment = manComment;
       this.contact = contact;
       this.roadmapUrl = roadmapUrl;
       this.chemicalUrl = chemicalUrl;
       this.packageUrl = packageUrl;
       this.chineese = chineese;
       this.key = key;
       this.xlpSeComponentsForManId = xlpSeComponentsForManId;
       this.xlpSeComponentsForOrgManId = xlpSeComponentsForOrgManId;
    }
   
    public long getManId() {
        return this.manId;
    }
    
    public void setManId(long manId) {
        this.manId = manId;
    }
    public String getManName() {
        return this.manName;
    }
    
    public void setManName(String manName) {
        this.manName = manName;
    }
    public String getManCode() {
        return this.manCode;
    }
    
    public void setManCode(String manCode) {
        this.manCode = manCode;
    }
    public String getManSiteUrl() {
        return this.manSiteUrl;
    }
    
    public void setManSiteUrl(String manSiteUrl) {
        this.manSiteUrl = manSiteUrl;
    }
    public String getManLogoUrl() {
        return this.manLogoUrl;
    }
    
    public void setManLogoUrl(String manLogoUrl) {
        this.manLogoUrl = manLogoUrl;
    }
    public String getManComment() {
        return this.manComment;
    }
    
    public void setManComment(String manComment) {
        this.manComment = manComment;
    }
    public String getContact() {
        return this.contact;
    }
    
    public void setContact(String contact) {
        this.contact = contact;
    }
    public String getRoadmapUrl() {
        return this.roadmapUrl;
    }
    
    public void setRoadmapUrl(String roadmapUrl) {
        this.roadmapUrl = roadmapUrl;
    }
    public String getChemicalUrl() {
        return this.chemicalUrl;
    }
    
    public void setChemicalUrl(String chemicalUrl) {
        this.chemicalUrl = chemicalUrl;
    }
    public String getPackageUrl() {
        return this.packageUrl;
    }
    
    public void setPackageUrl(String packageUrl) {
        this.packageUrl = packageUrl;
    }
    public Boolean getChineese() {
        return this.chineese;
    }
    
    public void setChineese(Boolean chineese) {
        this.chineese = chineese;
    }
    public Boolean getKey() {
        return this.key;
    }
    
    public void setKey(Boolean key) {
        this.key = key;
    }
    public Set getXlpSeComponentsForManId() {
        return this.xlpSeComponentsForManId;
    }
    
    public void setXlpSeComponentsForManId(Set xlpSeComponentsForManId) {
        this.xlpSeComponentsForManId = xlpSeComponentsForManId;
    }
    public Set getXlpSeComponentsForOrgManId() {
        return this.xlpSeComponentsForOrgManId;
    }
    
    public void setXlpSeComponentsForOrgManId(Set xlpSeComponentsForOrgManId) {
        this.xlpSeComponentsForOrgManId = xlpSeComponentsForOrgManId;
    }




}


